### ISSUE TITLE
Chore: Automate rename `master` branch to `main` 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/protect-main-branch#10]
At present _most_ of the repos in @dwyl have the `default` branch set to the "legacy" `master` ...
Given that the industry has moved to naming `default` branches to `main` see #8 
We need to automate it for the 

Looks fairly easy to do: https://docs.github.com/en/rest/branches/branches#rename-a-branch

# Todo

+ [ ] Write function that checks each repo for the `default` branch name
+ [ ] If the `default` repo is `master`, rename it to `main`
+ [ ] finally _protect_ the `main` branch
