### ISSUE TITLE
Name Change "Master" > "Main" ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/protect-main-branch#8]
Looks like we might be updating the name of this repo soon: 
https://www.bbc.com/news/technology-53050955

# Todo

+ [x] Make the necessary updates
+ [x] Test they are working by running the script on `localhost`
+ [x] Create PR: https://github.com/dwyl/protect-main-branch/pull/9
+ [x] Assign for review.

**Comment by nelsonic** [comment]
We've created a bunch of new repos in the last year and only a handful have the `main` branch protected ... by me, _manually_. Need to run this script across the whole org and in the process will update it from `master` to `main`. 💭

**Comment by nelsonic** [comment]
Attempted to run:

```sh
./protect --org dwyl --rules rules.json
```

But got the following error:

```sh
** (BadMapError) expected a map, got: {"documentation_url", "https://docs.github.com/rest"}
    :erlang.map_get("name", {"documentation_url", "https://docs.github.com/rest"})
    (protect 0.1.0) lib/protect.ex:79: anonymous fn/1 in Protect.get_repos/3
    (elixir 1.14.1) lib/enum.ex:1662: anonymous fn/3 in Enum.map/2
    (stdlib 4.1.1) maps.erl:411: :maps.fold_1/3
    (elixir 1.14.1) lib/enum.ex:2480: Enum.map/2
    (protect 0.1.0) lib/protect.ex:79: Protect.get_repos/3
    (protect 0.1.0) lib/protect.ex:20: Protect.main/1
    (elixir 1.14.1) lib/kernel/cli.ex:131: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

Tried stepping through the code but none the wiser ...
